language: php

cache:
    directories:
        - $HOME/.composer/cache/files
        - $HOME/symfony-bridge/.phpunit

env:
    global:
        - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"

jobs:
    fast_finish: true
    include:
        # Symfony 4.4
        -   php: 7.2
            env: SYMFONY_REQUIRE="4.4.*"
        -   php: 7.2
            env: SYMFONY_REQUIRE="4.4.*" COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        -   php: 7.3
            env: SYMFONY_REQUIRE="4.4.*"
        -   php: 7.3
            env: SYMFONY_REQUIRE="4.4.*" COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        -   php: 7.4
            env: SYMFONY_REQUIRE="4.4.*"
        -   php: 7.4
            env: SYMFONY_REQUIRE="4.4.*" COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        # Symfony 5.0
        -   php: 7.2
            env: SYMFONY_REQUIRE="5.0.*"
        -   php: 7.2
            env: SYMFONY_REQUIRE="5.0.*" COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        -   php: 7.3
            env: SYMFONY_REQUIRE="5.0.*"
        -   php: 7.3
            env: SYMFONY_REQUIRE="5.0.*" COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        -   php: 7.4
            env: SYMFONY_REQUIRE="5.0.*"
        -   php: 7.4
            env: SYMFONY_REQUIRE="5.0.*" COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        # Symfony 5.1
        -   php: 7.2
            env: SYMFONY_REQUIRE="5.1.*"
        -   php: 7.2
            env: SYMFONY_REQUIRE="5.1.*" COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        -   php: 7.3
            env: SYMFONY_REQUIRE="5.1.*"
        -   php: 7.3
            env: SYMFONY_REQUIRE="5.1.*" COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        -   php: 7.4
            env: SYMFONY_REQUIRE="5.1.*"
        -   php: 7.4
            env: SYMFONY_REQUIRE="5.1.*" COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

before_install:
    - composer global require --no-progress --no-scripts --no-plugins symfony/flex

install:
    - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
    - composer test install

script:
    - composer validate --strict --no-check-lock
    - composer lint -- --ansi --diff --dry-run
    - composer analyse -- --ansi --no-progress
    - composer test -- -v --coverage-text --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
