<?php

declare(strict_types=1);

namespace Bizkit\VersioningBundle\Writer;

use Bizkit\VersioningBundle\Version;

interface WriterInterface
{
    public const COMMENT = 'This file is generated by the bizkit versioning bundle';

    public function write(Version $version): void;
}
