name: Code Quality

on:
    push:
    pull_request:
    workflow_dispatch:
    schedule:
        -   cron: '0 8 * * *'

jobs:
    php-cs-fixer:
        runs-on: ubuntu-latest
        name: Coding Standards
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.1'
                    coverage: none
                    tools: php-cs-fixer, cs2pr

            -   name: Run PHP CS Fixer
                run: php-cs-fixer fix --dry-run --format checkstyle | cs2pr

    phpstan:
        runs-on: ubuntu-latest
        name: Static Analysis
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.1'
                    coverage: none
                    tools: phpstan

            -   name: Install Dependencies
                uses: ramsey/composer-install@v2
                with:
                    composer-options: '--prefer-dist'

            -   name: Install PHPUnit Dependencies
                run: vendor/bin/simple-phpunit install

            -   name: Run PHPStan
                run: phpstan analyse --no-progress
