name: Tests

on:
    push:
    pull_request:
    workflow_dispatch:
    schedule:
        -   cron: '0 8 * * *'

jobs:
    phpunit:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [ '8.1', '8.2', '8.3' ]
                symfony: [ '5.4', '6.4', '7.0' ]
                dependencies: [ 'highest', 'lowest' ]
                exclude:
                    -   php: '8.1'
                        symfony: '7.0'
        env:
            SYMFONY_REQUIRE: ${{ matrix.symfony }}.*
        name: PHP ${{ matrix.php }} & Symfony ${{ matrix.symfony }}${{ matrix.dependencies == 'lowest' && ' (lowest)' || '' }} Test
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    ini-values: zend.exception_ignore_args=false
                    tools: flex

            -   name: Install Dependencies
                uses: ramsey/composer-install@v2
                with:
                    composer-options: '--prefer-dist'
                    dependency-versions: ${{ matrix.dependencies }}

            -   name: Install PHPUnit Dependencies
                run: vendor/bin/simple-phpunit install

            -   name: Run PHPUnit
                run: vendor/bin/simple-phpunit -v --coverage-text --coverage-clover=coverage.xml

            -   name: Upload Coverage to Codecov
                if: ${{ success() }}
                uses: codecov/codecov-action@v4
                with:
                    file: coverage.xml
                    flags: ${{ matrix.php }}
                    token: ${{ secrets.CODECOV_TOKEN }}
